version: '3.8'

services:
  php:
    build:
      context: ./php
    container_name: symfony_php
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:rootpassword@db:3306/symfony_db
    command: php -S 0.0.0.0:8000 -t public
  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony_db
    ports:
      - "3306:3306"
